### ISSUE TITLE
test fails on humble

### ISSUE THREAD

**Issue by nonanonno** [nonanonno/rcld#17]
```
task: [test:all] . test_helper/ament/install/setup.sh
dub test --root test/rcld_test

Warning: License in subpackage rcld:test_msgs is different than it's parent package, this is discouraged.
Generating test runner configuration 'rcld_test-test-library' for 'library' (library).
Running pre-generate commands for rcld:test_helper...
test_msgs is already installed.
Performing "unittest" build using /opt/dlang/dmd-2.100.0/linux/bin64/dmd for x86_64.
rcld:rcl_bind ~test/add-test_msgs: target for configuration "library" is up to date.
rcld ~test/add-test_msgs: building configuration "library"...
pegged 0.4.6: target for configuration "default" is up to date.
rcld:test_helper ~test/add-test_msgs: building configuration "library"...
rcld:test_msgs ~test/add-test_msgs: building configuration "library"...
rcld_test ~master: building configuration "rcld_test-test-library"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running test/rcld_test/.dub/unittest/rcld_test-test-library 
 ✓ test_client __unittest_L18_C1
 ✓ test_publisher check if the topic created by the publisher found
Traceback (most recent call last):
  File "/rcld/test_helper/ament/install/test_msgs/local/lib/python3.10/dist-packages/test_msgs/srv/_basic_types.py", line 639, in float32_value
    assert value >= -3.402823e+38 and value <= 3.402823e+38, \
AssertionError: The 'float32_value' field must be a float in [-3.402823e+38, 3.402823e+38]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.3', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2service/command/service.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2service/verb/call.py", line 58, in main
    return requester(
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2service/verb/call.py", line 103, in requester
    rclpy.spin_until_future_complete(node, future)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 248, in spin_until_future_complete
    executor.spin_until_future_complete(future, timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 288, in spin_until_future_complete
    self.spin_once_until_future_complete(future, timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 715, in spin_once_until_future_complete
    self.spin_once(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 712, in spin_once
    raise handler.exception()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 411, in handler
    arg = take_from_wait_list(entity)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 347, in _take_client
    return client.handle.take_response(client.srv_type.Response)
SystemError: <built-in method take_response of PyCapsule object at 0x7f6f0ed48b70> returned a result with an exception set
 ✗ test_service check if the service created by the server can be found
    core.exception.AssertError thrown from test/rcld_test/source/test_service.d on line 58: unittest failure
    --- Stack trace ---
    ??:? _d_unittestp [0x55c277cbc175]
    test/rcld_test/source/test_service.d:58 void test_service.__unittest_L17_C1() [0x55c277caa9e5]
 ✓ test_subscription check if the topic created by the subscription can be found

Summary: 3 passed, 1 failed in 2144 ms
Program exited with code 1
```

**Comment by nonanonno** [comment]
Related to https://github.com/ros2/rosidl_python/pull/167/files
